const expect = require('chai').expect;
const { spice } = require('..');
const expectAlmostEqual = require('./utility/expectAlmostEqual');

describe('rotate', function() {
  it('should calculate the 3x3 rotation matrix generated by a rotation \
of a specified angle about a specified axis',
  function() {

    const actual = spice.rotate(3.14159265358979/2, 3);

    const expected = [[0, 1, 0], [-1, 0, 0], [0, 0, 1]];

    const tolerance = 1e-6;
    expectAlmostEqual(actual, expected, tolerance); 
  });
});
